sonar.verbose=true
sonar.organization=jp-sqorg
sonar.projectKey=jp-sqorg-jptrend
sonar.projectName=jptrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.average.jacoco.xml.reportPaths=target/site/jacoco/jacoco.xml